urls.py
__author__ = 'kirill'


from django.conf.urls import url
from KaiHostel3.views import *

app_name="KaiHostel3"

urlpatterns=[
    url(r'^$',index),
    url(r'login/$',Login.as_view(),name='login'),
    url(r'logout/$',Logout.as_view(),name='logout'),
    url(r'add_article/$',AddArticle.as_view(),name='add_article'),
    url(r'articles/?page=(?P<page>[0-9]+)/$',AllArticle.as_view(),name='all_article'),
    url(r'detail_article/(?P<pk>[0-9]+)/$',GetArticle.as_view(),name='detail_article'),
    url(r'register/$',Register.as_view(),name='register'),
    url(r'add_comment/$',AddComment.as_view(),name='add_comment'),
    url(r'all_comment/$',AllComment.as_view(),name='all_comment'),
    url(r'del_comment/(?P<article_id>[0-9]+)/$',DeleteArticle.as_view(),name='del_article')
]

models.py
from django.db import models
from django.contrib.auth.models import User,AnonymousUser
from django.utils import timezone
# Create your models here.


class UserProfile(models.Model):
    user=models.OneToOneField(User)
    website=models.URLField(blank=True,default='')
    photo=models.ImageField(upload_to='profile_images',blank=True)

    def __str__(self):
        if self.user:
             return self.user.username
        else:
            return ''

class Tags(models.Model):
    title=models.CharField(max_length=100)

    def __str__(self):
        return self.title

class Comment(models.Model):
    owner=models.ForeignKey(UserProfile,default=None,null=True,unique=False)
    article=models.ForeignKey('Article',on_delete=models.CASCADE,unique=False,default=None)
    content=models.TextField(max_length=300,default='',unique=False,blank=True)
    pub_date=models.DateTimeField(default=timezone.now)
    parent=models.ForeignKey('self',default=None,null=True,blank=True,unique=False)

    username=models.CharField(max_length=100,default='',blank=True,unique=False)

    def __str__(self):
        if self.owner:
            return self.owner.__str__()
        else:
            return 'By anonyomous: {0}'.format(self.username)

    def get_root_comment(self,comment=None):
        pass

class Article(models.Model):
    article=models.CharField(max_length=200,default='')
    user_profile=models.ForeignKey(UserProfile,unique=False,default=None)
    pub_date=models.DateTimeField(default=timezone.now)
    content=models.TextField(default='')
    tags=models.ManyToManyField(Tags,
                           default=None,
                           blank=True,
                           )

    def __str__(self):
        return self.article

    def get_short_description(self):
        if self.content.__len__()>400:
            return self.content[:400]+'...'
        else:
            return self.content


    class Meta:
        ordering=['-pub_date']

templates/KaiHostel3/add_article.html
{% extends 'KaiHostel3/base.html' %}

{% block content %}
    <div id="content">
<form method="post" name="add_article">
    {% csrf_token %}
    {{ form.as_ul }}
    <input type="submit" value="Add article">
</form>
    </div>
{% endblock %}

templates/KaiHostel3/add_comment.html
{% extends 'KaiHostel3/base.html' %}

{% block content %}
    <div id="content">
        You can add comment here
        <form method="post" name="post">
            {% csrf_token %}
            {% if not user.is_authenticated %}
                <div name="'if_user_auth">
                    You need put some information about yourself:
                    <p>
                        <input name="username" type="text">
                    </p>

                    <p>
                        <input type="url" name="website">
                    </p>

                    <p>
                        <input type="file" name="photo">
                    </p>
                </div>

            {% endif %}
            {{ form.as_ul }}
            <input type="submit">
        </form>
    </div>
{% endblock %}

templates/KaiHostel3/all_article.html
{% extends 'KaiHostel3/base.html' %}
{% block title %}
    Все записи
{% endblock %}
{% block content %}
    <div id="content">
        {% if article_list %}
            {% for article in article_list %}
                <div id='article'>
                    <div id="article_information">
                        <div id="article_description">
                            <H3>
                                {#  <div id="article_name">#}
                                <a href="{% url 'KaiHostel3:detail_article'  article.id %}">
                                    {{ article.article }}
                                </a>
                            </H3>
                            {#</div>#}
                            <div id="article_owner">
                                <H4>Owner:</H4>
                                {{ article.user_profile }}
                            </div>
                            <div id="article_pub_date">
                                <H4>Publication date:</H4>
                                {{ article.pub_date|date:"D d M Y" }}
                            </div>

                        </div>
                        {% if user.userprofile == article.user_profile%}
                            <div id="article_action">
                                <div>
                                    <H2>My action:</H2>

                                    <p>
                                        <a href="{% url 'KaiHostel3:del_article' article.id %}">
                                            Delete an article
                                        </a>
                                    </p>
                                </div>
                            </div>
                        {% endif %}
                        <div id="article_comment_count">
                            Comment {{ article.comment_set.count }} in total
                        </div>
                    </div>
                    <div id="article_short_content">
                        <H2>Article's title:</H2>{{ article.get_short_description }}
                    </div>
                    {% include 'KaiHostel3/tags.html' %}
                </div>
            {% endfor %}
            {# ..... **Now th pagination section** .... #}
            {% if is_paginated %}
                <div id="pagination">
                    <div class="page-links">
                        {% if page_obj.has_previous %}
                            <a href="{% url 'KaiHostel3:all_article' page_obj.previous_page_number %}">Previous page</a>
                        {% endif %}
                        <div class="page-current">
                            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
                        </div>
                        {% if page_obj.has_next %}
                            <a href="{% url "KaiHostel3:all_article" page_obj.next_page_number %}">Next</a>
                        {% endif %}
                    </div>
                </div>
            {% endif %}
        {% else %}
            <H2>There are not any articles.
                {% if user.is_authenticated %}
                    Please,add the new one <a href="{% url 'KaiHostel3:add_article' %}">here</a></H2>
                {% endif %}
        {% endif %}
        {# .... **More content,footer,etc.**.... #}
    </div>
{% endblock %}



<H3>
    {#  <div id="article_name">#}
    <a href="{% url 'KaiHostel3:detail_article'  article.id %}">
        {{ article.article }}
    </a>
</H3>
{#</div>#}
<div id="article_owner">
    <H4>Owner:</H4>
    {{ article.user_profile }}
</div>
<div id="article_pub_date">
    <H4>Publication date:</H4>
    {{ article.pub_date|date:"D d M Y" }}
</div>

templates/KaiHostel3/all_comment.html
{% extends 'KaiHostel3/base.html' %}

{% block content %}
    <div id="content">
{% if error %}
    You have not been signed in
{% else %}
    {% if list %}
        {% for comment in list %}
            <div id="comment">
                <H2>{{ comment.owner }}</H2>
                <H3>{{ comment.pub_date }}</H3>
                <H4>{{ comment.content }}</H4>
            </div>
        {% endfor %}
    {% endif %}
{% endif %}
    </div>
{% endblock %}

templates/KaiHostel3/article.html
{% extends 'KaiHostel3/base.html' %}

{% block content %}
    <div id="content">
        {% if article %}
            <div id="article">
                <H1>{{ article.article }}</H1>

                <div id="article_detail_pub_date"> Publication_date: {{ article.pub_date|date:"D d M Y" }}</div>

                <div id="article_detail_userprofile"> Customer:{{ article.user_profile }}</div>
                <div id="article_detail_content"><H3>{{ article.content }}</H3></div>
                <div id="article_detail_tags">
                    {% if article.tags %}
                        {% for tag in article.tags.all %}
                            <div id="tag">{{ tag.title }}</div>
                        {% endfor %}
                    {% else %}
                        There are not any tags for this article
                    {% endif %}
                </div>

                <div id="article_all_comment">
                    <H3>Comments:</H3>
                    {% for com in article.comment_set.all %}
                        <div id="comment">
                        <div id="comment_data">{{ com.content }}</div>
                            <div id="comment_info">
                                {% if com.owner %}
                                    {{ com.owner }}-{{ com.pub_date }}
                                {% else %}
                                    By anon {{ com.username }}-{{ com.pud_date }}
                                {% endif %}

                            </div>


                        </div>
                    {% empty %}
                        <H6>Nobody left comment here</H6>
                    {% endfor %}
                </div>


                <div id="article_comment_add">
                    <form method="post" action="{% url 'KaiHostel3:add_comment' %}">
                        {% csrf_token %}
                        {% for field in form.visible_fields %}
                            <h3>{{ field.name|upper }}</h3>
                            <p>{{ field }}</p>
                        {% endfor %}
                         {% for field in form.hidden_fields %}
                            <p>{{ field }}</p>
                        {% endfor %}
                        <input type="submit" value="Add comment">
                    </form>
                </div>
            </div>
        {% endif %}
    </div>
{% endblock %}

templates/KaiHostel3/base.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    {% block referense_css %}
        {% load staticfiles %}
        <link href="{% static "KaiHostel3/bootstrap/css/bootstrap.css" %}" rel="stylesheet">
        <link href="{% static "KaiHostel3/bootstrap/css/bootstrap-responsive.css" %}" rel="stylesheet">
        <link href="{% static "KaiHostel3/css/base.css" %}" rel="stylesheet">
        <link href="{% static "KaiHostel3/css/article.css" %}" rel="stylesheet">
        <link href="{% static "KaiHostel3/css/menu.css" %}" rel="stylesheet">
    {% endblock %}
    <title>
        {% block title %}
        {% endblock %}
    </title>
<body>
{% load staticfiles %}
<script src="{% static 'KaiHostel3/bootstrap/js/bootstrap.min.js' %}"></script>



{% block header %}
    <div id="head">
        <div id="site_name">
            <H3>Blog's name</H3>
        </div>
        <div id="login-snippet">
            {% include 'KaiHostel3/login_snippet.html' %}
        </div>
    </div>
{% endblock %}


<div id="main">
{% block content %}
    <div id="content"></div>
{% endblock %}
{% block menu %}

    {% include 'KaiHostel3/menu.html' %}

{% endblock %}
</div>
{% block footer %}

{% endblock %}

</body>
</html>

templates/KaiHostel3/login.html
{% extends 'KaiHostel3/base.html' %}

{% block content %}
    <div id="content">
        {% if not user.is_authenticated %}
            <form method="post">
            {% csrf_token %}
            {{ form.as_ul }}
            <input type="submit" value="Login">
        {% else %}
            You've entered before
            <P>{{ user.user }}</P>
        {% endif %}
    </div>
{% endblock %}

templates/KaiHostel3/login_snippet.html
    {% if user.is_authenticated %}
        <p>Welcome, {{ user.username }}!</p>
        <p><a href="{% url 'KaiHostel3:logout' %}">Logout here</a></p>
    {% else %}
        {% if user.is_anonymous %}
            You are anonyomus!
            <P>Please,sign in <a href="{% url 'KaiHostel3:login' %}">here</a></P>
        {% endif %}
        Register <a href="{% url "KaiHostel3:register" %}">here</a>
    {% endif%}

templates/KaiHostel3/menu.html
<div id="menu">
    <H3>The main menu</H3>
    <H5><a href="{% url 'KaiHostel3:all_article' 1 %}">All articles</a></H5>
    {% if user.is_authenticated %}
        <H5><a href="{% url 'KaiHostel3:add_article' %}">Add article</a></H5>
         <br>
    <H5><a href="{% url 'KaiHostel3:all_comment' %}">My comments</a></H5>
    {% endif %}
    <H5><a href="{% url 'KaiHostel3:register' %}">Register</a></H5>
    <H5>
        {% if user.is_authenticated %}
            <a href="{% url 'KaiHostel3:logout' %}">Logout</a>
        {% else %}
            <a href="{% url 'KaiHostel3:login' %}">Login</a>
        {% endif %}
    </H5>
</div>

templates/KaiHostel3/register.html
{% extends 'KaiHostel3/base.html' %}

{% block content %}
    <div id="content">
        <H1>Registred form</H1>
        {% if registred %}
            <strong>Thanks for your registration</strong>
            <a href="{% url "Blog:all_article" 1 %}">Return to all article</a>
        {% else %}
            <strong>Register here</strong>
            <form id="user_form" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ user_form.as_p }}
                {{ profile_form.as_p }}
                <input type="submit" name="submit" value="Register">
            </form>
        {% endif %}
    </div>
{% endblock %}

templates/KaiHostel3/tags.html
<div id="article_tags">
    {% if article.tags.count != 0 %}
        Tags:
        {% for tag in article.tags.all %}
            <div id="tag">
                {{ tag.title }}
            </div>
        {% endfor %}
    {% endif %}
</div>